export const users = [
  {
    name: 'Admin Royal Shopping',
    email: 'admin@revibe.com',
    password: 'adminpassword123',
    role: 'ADMIN',
    phone: '+91 98765 43210',
    address: {
      fullName: 'Admin Operations',
      phone: '+91 98765 43210',
      address: 'Suite 404, Tech Park',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560001',
    },
  },
  {
    name: 'Tharun Kumar',
    email: 'tharun@revibe.com',
    password: 'userpassword123',
    role: 'USER',
    phone: '+91 91234 56789',
    address: {
      fullName: 'Tharun Kumar',
      phone: '+91 91234 56789',
      address: '142 Palm Grove Avenue',
      city: 'Hyderabad',
      state: 'Telangana',
      postalCode: '500081',
    },
  },
];

export const categories = [
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Cutting-edge audio, smart wearables, and premium personal tech.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Fashion',
    slug: 'fashion',
    description: 'Contemporary apparel, minimalist streetwear, and timeless wardrobe staples.',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Beauty',
    slug: 'beauty',
    description: 'Botanical skincare, organic haircare, and luxury wellness formulations.',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Home',
    slug: 'home',
    description: 'Artisanal ceramics, ambient lighting, and modern Scandinavian home decor.',
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Precision handcrafted leather goods, chronographs, and everyday carries.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Sports',
    slug: 'sports',
    description: 'Performance gear, smart hydration, and athletic essentials.',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
    isActive: true,
  },
];

export const getSeedProducts = (categoryMap) => [
  {
    name: 'Sony WH-1000XM5 Noise-Canceling Headphones',
    brand: 'Sony',
    category: categoryMap['Electronics'],
    description: 'Industry-leading noise cancellation optimized to you with two processors and 8 microphones. Magnificent audio quality engineered to perfection with the new Integrated Processor V1. Up to 30-hour battery life with quick charging.',
    specifications: [
      { key: 'Driver Unit', value: '30mm, Carbon Fiber Composite' },
      { key: 'Battery Life', value: 'Up to 30 Hours (NC ON)' },
      { key: 'Connectivity', value: 'Bluetooth 5.2, LDAC, Hi-Res Audio' },
      { key: 'Weight', value: '250g' },
    ],
    price: 26990,
    discountPrice: 24490,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
    ],
    stock: 18,
    rating: 4.8,
    numReviews: 124,
    featured: true,
  },
  {
    name: 'Apple Watch Series 9 GPS 45mm Aluminum',
    brand: 'Apple',
    category: categoryMap['Electronics'],
    description: 'Smarter. Brighter. Mightier. The S9 chip powers a magical new gesture interaction — Double Tap. Enjoy an edge-to-edge Always-On Retina display with up to 2000 nits of brightness.',
    specifications: [
      { key: 'Display', value: 'Always-On Retina OLED (2000 nits)' },
      { key: 'Processor', value: 'Apple S9 SiP 64-bit dual-core' },
      { key: 'Water Resistance', value: '50 meters (Swimproof)' },
      { key: 'Sensors', value: 'ECG, Blood Oxygen, Temperature' },
    ],
    price: 44900,
    discountPrice: 41900,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
    ],
    stock: 12,
    rating: 4.9,
    numReviews: 98,
    featured: true,
  },
  {
    name: 'Marshall Emberton II Portable Bluetooth Speaker',
    brand: 'Marshall',
    category: categoryMap['Electronics'],
    description: 'Emberton II delivers sound that is rich, clear, and loud, like Marshall intended. Experience absolute 360° sound with True Stereophonic, a unique form of multi-directional sound.',
    specifications: [
      { key: 'Playtime', value: '30+ Hours' },
      { key: 'Water Resistance', value: 'IP67 Dust & Waterproof' },
      { key: 'Frequency Range', value: '60 Hz – 20 kHz' },
    ],
    price: 17499,
    discountPrice: 15999,
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
    ],
    stock: 25,
    rating: 4.7,
    numReviews: 62,
    featured: true,
  },
  {
    name: 'Minimalist Relaxed Fit Linen Overshirt',
    brand: 'Zara',
    category: categoryMap['Fashion'],
    description: 'Crafted from 100% sustainably sourced European flax linen. Features a relaxed silhouette with mother-of-pearl buttons and double chest flap pockets. Breathable and effortlessly refined.',
    specifications: [
      { key: 'Material', value: '100% Pure European Linen' },
      { key: 'Fit', value: 'Relaxed Oversized Fit' },
      { key: 'Care', value: 'Machine wash cold delicate' },
    ],
    price: 4990,
    discountPrice: 3890,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
    ],
    stock: 30,
    rating: 4.6,
    numReviews: 44,
    featured: false,
  },
  {
    name: 'Organic Heavyweight French Terry Hoodie',
    brand: 'Nike',
    category: categoryMap['Fashion'],
    description: '450 GSM custom knit heavyweight organic cotton. Designed with dropped shoulders, a structured double-layer hood, and seamless kangaroo pocket for everyday luxury comfort.',
    specifications: [
      { key: 'Fabric', value: '450 GSM 100% Organic Cotton' },
      { key: 'Origin', value: 'Made in Portugal' },
      { key: 'Details', value: 'Ribbed hems and cuffs' },
    ],
    price: 6499,
    discountPrice: 5299,
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80',
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&q=80',
    ],
    stock: 19,
    rating: 4.8,
    numReviews: 87,
    featured: true,
  },
  {
    name: 'Aesop Parsley Seed Anti-Oxidant Intense Serum',
    brand: 'Aesop',
    category: categoryMap['Beauty'],
    description: 'A potent, lightweight hydrating serum formulated with antioxidant-rich botanical extracts and vitamins to fortify the skin against airborne pollutants and environmental stressors.',
    specifications: [
      { key: 'Volume', value: '60 ml / 2.0 fl oz' },
      { key: 'Key Ingredients', value: 'Parsley Seed, Tocopherol, Red Algae' },
      { key: 'Skin Type', value: 'Normal, Combination, and Sensitive' },
    ],
    price: 7800,
    discountPrice: 7200,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80',
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80',
    ],
    stock: 22,
    rating: 4.9,
    numReviews: 53,
    featured: true,
  },
  {
    name: 'Byredo Mojave Ghost Eau De Parfum 100ml',
    brand: 'Byredo',
    category: categoryMap['Beauty'],
    description: 'A soulful woody composition inspired by the soulful beauty of the Mojave Desert. Top notes of ambrette and Jamaican nesberry lead to powdery violet, sandalwood, and crisp amber.',
    specifications: [
      { key: 'Concentration', value: 'Eau de Parfum' },
      { key: 'Size', value: '100ml' },
      { key: 'Fragrance Family', value: 'Woody Floral' },
    ],
    price: 21500,
    discountPrice: 19999,
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=80',
      'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&q=80',
    ],
    stock: 8,
    rating: 4.7,
    numReviews: 38,
    featured: false,
  },
  {
    name: 'Nordic Ceramic Matte Ribbed Vase',
    brand: 'Royal Home',
    category: categoryMap['Home'],
    description: 'Hand-thrown stoneware with a tactile matte glazed finish. Designed to hold dry botanicals or fresh seasonal stems with sculptural grace on dining tables and consoles.',
    specifications: [
      { key: 'Material', value: 'High-fire Matte Ceramic' },
      { key: 'Dimensions', value: '28cm H x 16cm Dia' },
      { key: 'Finish', value: 'Sand White Glaze' },
    ],
    price: 3499,
    discountPrice: 2899,
    images: [
      'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=800&q=80',
      'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=800&q=80',
    ],
    stock: 14,
    rating: 4.5,
    numReviews: 29,
    featured: false,
  },
  {
    name: 'Aroma Diffuser & Ambient Warm Light Lamp',
    brand: 'Muji',
    category: categoryMap['Home'],
    description: 'Ultrasonic wave technology vaporizes water and essential oils to create a fragrant, cool mist. Features dual warm LED light settings that double as a bedside night lamp.',
    specifications: [
      { key: 'Capacity', value: '350 ml' },
      { key: 'Coverage', value: '200-250 sq ft' },
      { key: 'Timer Modes', value: '60 / 120 / 180 min' },
    ],
    price: 4999,
    discountPrice: 4299,
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&q=80',
    ],
    stock: 35,
    rating: 4.6,
    numReviews: 71,
    featured: true,
  },
  {
    name: 'Handcrafted Full-Grain Leather Bi-fold Wallet',
    brand: 'Fossil',
    category: categoryMap['Accessories'],
    description: 'Vegetable-tanned full-grain Italian leather with RFID blocking protection. Hand-stitched with bonded nylon thread, gaining a deep, lustrous patina over years of daily carry.',
    specifications: [
      { key: 'Material', value: 'Italian Full-Grain Vegetable Leather' },
      { key: 'Capacity', value: '8 Card Slots, 2 Cash Sleeves' },
      { key: 'RFID Protection', value: 'Yes (13.56 MHz)' },
    ],
    price: 3290,
    discountPrice: 2690,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
      'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&q=80',
    ],
    stock: 40,
    rating: 4.8,
    numReviews: 110,
    featured: true,
  },
  {
    name: 'Ray-Ban Classic Polarized Clubmaster Sunglasses',
    brand: 'Ray-Ban',
    category: categoryMap['Accessories'],
    description: 'Timeless retro vintage styling with polished black acetate browline, gold metal accents, and crystal green G-15 polarized lenses with 100% UV protection.',
    specifications: [
      { key: 'Frame Material', value: 'Acetate & Polished Metal' },
      { key: 'Lens', value: 'G-15 Polarized Crystal' },
      { key: 'Frame Size', value: '51-21 145' },
    ],
    price: 11290,
    discountPrice: 9990,
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80',
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80',
    ],
    stock: 16,
    rating: 4.7,
    numReviews: 89,
    featured: false,
  },
  {
    name: 'Hydro Flask 32oz Insulated Stainless Steel Tumbler',
    brand: 'Hydro Flask',
    category: categoryMap['Sports'],
    description: 'TempShield double-wall vacuum insulation keeps cold beverages ice-cold for 24 hours or piping hot for 12 hours. Features a leak-proof flex chug cap and non-slip powder coat.',
    specifications: [
      { key: 'Volume', value: '946 ml / 32 oz' },
      { key: 'Material', value: 'Pro-Grade 18/8 Stainless Steel' },
      { key: 'BPA Free', value: 'Yes' },
    ],
    price: 3890,
    discountPrice: 3290,
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80',
      'https://images.unsplash.com/photo-1570824104453-508955ab713e?w=800&q=80',
    ],
    stock: 50,
    rating: 4.9,
    numReviews: 145,
    featured: true,
  },
];
